APP1/urls.py
from django.urls import path, include

from . import views

app_name = 'APP1'

urlpatterns = [
    path('', views.index, name='index'),
]

corona_app/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from feedback.views import olah

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('APP1.urls')),
    path('forums/', include('forums.urls')),
    path('news/', include('news.urls')),
    path('userProfile/', include('userProfile.urls')),
    path('feedback/', include('feedback.urls')),
    path('rate/', olah, name = "olah"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userProfile/urls.py
from django.urls import path
from . import views

app_name = 'userProfile'

urlpatterns = [
	path('signup/',views.signup_view,name="signup"),
	path('logout/',views.logout_view,name="logout"),
	path('login/',views.login_view,name="login"),
	path('profile/',views.profile_view,name="profile"),
	path('picupdate/',views.picupdate,name="picUpdate"),
]

userProfile/models.py
from os import truncate
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import MinValueValidator

# Create your models here.

class Account(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	name = models.CharField(max_length=150, null=True)
	email = models.EmailField(max_length=200, null=True)
	job	 = models.CharField(max_length=50, null=True)
	age  = models.PositiveIntegerField(validators=[MinValueValidator(1)])
	image = models.TextField(default='/static/APP1/icon/profile_default.png', null=True, blank=True)
	profilepicture = models.ImageField(default='profile_default.png', null=True, blank=True)

	def __str__(self):
		return self.user.username
	

	

userProfile/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Account
from django.utils.translation import gettext_lazy as _

class SignupForm(UserCreationForm):
	class Meta(UserCreationForm.Meta):
		fields = UserCreationForm.Meta.fields + ("email",)
		labels = {
			'email': 'Email',
		}

class AccountForm(forms.ModelForm):
	class Meta:
		model = Account
		fields = ['job','age']

class ProfileSettingsForm(forms.ModelForm):
	class Meta:
		model = Account
		fields = '__all__'
		exclude = ['user', 'image']

userProfile/views.py
from django.shortcuts import render, redirect
from .forms import SignupForm, AccountForm, ProfileSettingsForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from .models import *
from django.contrib import messages
from django.http import JsonResponse, HttpResponse
import json
# Create your views here.


def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        account_form = AccountForm(request.POST)
        if form.is_valid() and account_form.is_valid():
            user = form.save()
            account = account_form.save(commit=False)
            account.user = user
            account.name = user.username
            account.email = user.email
            account.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)

            return redirect('APP1:index')
    else:
        form = SignupForm()
        account_form = AccountForm()

    context = {'form': form, 'account_form': account_form}
    return render(request, 'userProfile/signup.html', context)


@login_required(login_url='/userProfile/login')
def logout_view(request):
    logout(request)
    return redirect('APP1:index')


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect('APP1:index')
        else:
            messages.info(request, 'Username OR password is incorrect')
    context = {}
    return render(request, 'userProfile/login.html', context)


@login_required(login_url='/userProfile/login')
# @allowed_users(allowed_roles=['account'])
def profile_view(request):
    account = request.user.account
    form = ProfileSettingsForm(instance=account)

    context = {'form': form, 'account': account}
    return render(request, 'userProfile/profile.html', context)

@login_required(login_url='/userProfile/login')
def picupdate(request):
    account = request.user.account
    form = ProfileSettingsForm(instance=account)

    if request.method == 'POST':
        form = ProfileSettingsForm(
            request.POST, request.FILES, instance=account)
        if form.is_valid():
            ins = form.save()
            if request.FILES.get('profilepicture'):
                import os
                import base64
                from corona_app.settings import MEDIA_ROOT
                file_path = os.path.join(MEDIA_ROOT, str(request.FILES.get('profilepicture')))
                with open(file_path, "rb") as img_file:
                    my_string = "data:image/png;base64,"+str(base64.b64encode(img_file.read()).decode('utf-8'))
                ins.image = my_string
                data = {
                    'message' : 'Your profile picture so cool!😎',
                    'imgLoc' : account.profilepicture.url[16:],
                    'img' : my_string,
                }
                ins.save()
                
                return JsonResponse(data)
            # elif request.POST.get('profilepicture-clear') != None:
            #     imgLoc = '/static/APP1/icon/profile_default.png'
            #     ins.image = imgLoc
            #     ins.save()
            #     data = {
            #         'message' : 'Your profile picture so ugly!😈',
            #         'img' : imgLoc
            #     }
            #     return HttpResponse(json.dumps(data))
            else:
                data = {
                    'message' : 'Profile updated successfully!😊',
                    'img' : account.image,
                    'imgLoc' : account.profilepicture.url[16:],
                }
                return JsonResponse(data)

userProfile/templates/userProfile/login.html
{% extends 'APP1/base.html' %}
{% load static  %}
{% block head %}
    <link rel="stylesheet" href="{% static 'userProfile.css' %}">
{% endblock head %}

{% block body %}
    <div id ="signup">
		<div class = "card z-depth-3">
			<div class ="card-panel center pink lighten-2">
				<span class = "card-title">Login</span>
			</div>
            <form class = "site-form" action="/userProfile/login/" method="post" >
                {% csrf_token %}
                <div class ="input-field">
                    <i class ="material-icons prefix">face</i>
                    <label for="username">Username</label>
                    <input id="username" type="text" name="username">
                </div>
                <div class ="input-field">
                    <i class ="material-icons prefix">lock</i>
                    <label for="password">Password</label>
                    <input id="password" type="password" name="password">
                </div>

                
                {% for message in messages %}
                    <p style="color: red;">{{message}}</p>
                {% endfor %}
                
                <div>
                    <p>Don't have an account? <a href="/userProfile/signup/"> Sign up</a></p>
                </div>

                <div class ="center">
                    <input type="submit" value = "Log In" class = "btn-large pink lighten-2">
                </div>
            </form>
        </div>
	</div>

{% endblock body %}

{% block script %}
{% endblock script %}

userProfile/templates/userProfile/profile.html
{% extends 'APP1/base.html' %}
{% load static %}
{% block head %}
	<link rel="stylesheet" href="{% static 'userProfile.css' %}">
	<style type="text/css">
		#profilepicture-clear_id {
 			 display: none;
		}
		label[for=profilepicture-clear_id]{
			display: none;
		}
	</style>
	
{% endblock %}
{% block body %}

<div class="container">
<div class="row">
	<div class="col l3 s12">
		<div style="text-align: center; padding: 10px;" class="card card-body">
			<a class="btn waves-effect waves-light" href="{% url 'APP1:index' %}"
			style="
			background: white;
			color: #da4167;
			border-radius: 5px;
			margin-bottom: 10px;
			border: #da4167 1.6px solid;
			"
			> 
				&#8592; Back to 🏠
			</a>
			<li class="divider" tabindex="-1"></li>
			<p class="flow-text">Profile Settings</p>
			<div id="profilepic">
				<img class="profile-pic" src="{{request.user.account.image}}">
			</div>
			
		</div>
	</div>
	<div class="col l9 s12">
		<div style="padding: 10px;" class="card card-body">
			<form class="profileset" method="POST" action="" id="profileform" enctype="multipart/form-data">
				{% csrf_token %}
				<div>
					<label for="id_name">Name:</label>
					{{form.name}}	
				</div>
				<div>
					<label for="id_email">Email:</label>
					{{form.email}}
				</div>
				<div>
					<label for="id_job">Job:</label>
					{{form.job}}
				</div>
				<div>
					<label for="id_age">Age:</label>
					{{form.age}}
				</div>
				<div id="setpict">
					{{ form.profilepicture }}
				</div>
				<div class="z-depth-1" id="messages"
					style="padding: 6px;
					font-size: .8rem;
					margin-bottom: 10px;
					color: #15c06d; 
					height: fit-content; 
					border-radius: 5px; 
					width: fit-content;
					background: white">
				</div>
				
				<div >
				</div>
				<button class="btn waves-effect waves-light" type="button" name="action"
				style="background: #832161; border-radius: 5px;"
				>
					Submit
					<i class="material-icons right">send</i>
				</button>
			</form>
		</div>
	</div>
</div>
</div>
{% endblock body %}

{% block script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script type="text/javascript">
	var objRes = $('#messages')

	function readURL(input) {
		
		if (input.files && input.files[0]){
			var reader = new FileReader();

			reader.onload = function (e) {
				$('.profile-pic').attr('src',e.target.result);
				
			}

			reader.readAsDataURL(input.files[0]);
		}
	}

	$('#id_profilepicture').change(function(){
		objRes.empty()
		readURL(this);
	})


	$('#profileform .btn').click(function () {
		$.ajax({
			url: '/userProfile/picupdate/',
			type: 'POST',
			data: new FormData(profileform),
			processData: false,
			contentType: false,
			success: function(response){
				var setpict=$('#setpict')
				// var myRes = JSON.parse(response);
				objRes.empty();
				console.log("success");
				console.log(response.message);
				objRes.append(response.message);
				$('.profile-pic').attr('src',response.img);
				$('.profile__img').attr('src',response.img);
				setpict.empty();
				setpict.append('Currently: '+ '<a href="'+ response.imgLoc + '">'+ response.imgLoc+'</a>' );
				setpict.append('<br> Change: '+'<input type="file" name="profilepicture" accept="image/*" id="id_profilepicture">');
			}
		});
		
	});
</script>>
{% endblock script %}

userProfile/templates/userProfile/signup.html
{% extends 'APP1/base.html' %}
{% load static  %}
{% block head %}
	<link rel="stylesheet" href="{% static 'userProfile.css' %}">
{% endblock head %}

{% block body %}
	<div id ="signup">
		<div class = "card z-depth-3">
			<div class ="card-panel center pink lighten-2">
				<span class = "card-title">Sign Up</span>
			</div>
			<form class="site-form" action="/userProfile/signup/" method="post">	
				{% csrf_token %}
				
				{% for field in form %}
					{{field.label}}
					{{field}}
				{% endfor %}
				{{ account_form }}

				{{form.errors}}

				<div>
                    <p>Already have an account? <a href="/userProfile/login/"> Login</a></p>
                </div>

				<div class ="center">
					<input type="submit" value = "Sign Up" class = "btn-large pink lighten-2">
				</div>
			</form>
		</div>
	</div>	
{% endblock body %}

{% block script %}
<script>
	var err_messsage = document.getElementsByClassName('errorlist')
	
	for (var key in err_messsage) {
		err_messsage[key].className += ' browser-default'
	}
</script>
{% endblock script %}