APP1/urls.py
from django.urls import path, include

from . import views

app_name = 'APP1'

urlpatterns = [
    path('', views.index, name='index'),
]

corona_app/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from feedback.views import olah

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('APP1.urls')),
    path('forums/', include('forums.urls')),
    path('news/', include('news.urls')),
    path('userProfile/', include('userProfile.urls')),
    path('feedback/', include('feedback.urls')),
    path('rate/', olah, name = "olah"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forums/urls.py
from django.urls import path

from . import views

app_name = 'forums'

urlpatterns = [
    path('', views.forums, name='forums'),
    path('add_forum/', views.add_forum, name='forums_add_forum'),
    path('<int:pk>', views.detail_forum, name='forums_detail_forum'),
    path('delete_forum/<int:pk>', views.delete_forum, name='forums_delete_forum'),
    path('search/', views.ajax_search, name='forums_search'),
    path('set_follow/', views.ajax_set_follow, name='forums_set_follow'),
    path('get_follow/', views.ajax_get_follow, name='forums_get_follow'),
]

userProfile/urls.py
from django.urls import path
from . import views

app_name = 'userProfile'

urlpatterns = [
	path('signup/',views.signup_view,name="signup"),
	path('logout/',views.logout_view,name="logout"),
	path('login/',views.login_view,name="login"),
	path('profile/',views.profile_view,name="profile"),
	path('picupdate/',views.picupdate,name="picUpdate"),
]

forums/models.py
from django.db import models
from userProfile.models import Account
from django.db.models.deletion import CASCADE

class Forum(models.Model):
    caption = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    body = models.TextField()
    author = models.ForeignKey(Account, default=None, on_delete=CASCADE, related_name="+")

    followed_by = models.ManyToManyField(Account, default=None)
    class Meta:
        ordering = ['-timestamp']

class Comment(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    body = models.TextField()
    forum = models.ForeignKey(Forum, related_name="comments", on_delete=CASCADE)
    author = models.ForeignKey(Account,  default=None, on_delete=CASCADE)

forums/forms.py
from django import forms
from django.forms.widgets import Textarea
from .models import Forum, Comment

class ForumForm(forms.ModelForm):
    
    class Meta:
        model = Forum
        exclude = ['author','followed_by']
        widgets = {
            'caption': Textarea(
                attrs={
                    'placeholder' : 'Write a caption...',
                    'class'       : 'materialize-textarea'
                    }),
            'body'  : Textarea(
                attrs={
                    'class'       : 'materialize-textarea',
                    'id'          : 'textarea1'
                    }),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ['author']
        widgets = {
            'body'  : Textarea(
                attrs={
                    'placeholder' : 'Add a comment...',
                    'class'       : 'materialize-textarea',
                    }),
        }

forums/views.py
from userProfile.models import Account
from django.core.serializers import serialize
from django.db.models.query_utils import Q
from django.http.request import HttpRequest
from django.http.response import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from .models import Forum
from .forms import ForumForm, CommentForm
import json


def forums(request, warn=False):
    request.session['forums_item'] = Forum.objects.all().count()
    context = {
        'forums': Forum.objects.all(),
        'warn': warn
    }
    return render(request, 'forums/forums.html', context)


def add_forum(request):
    if not request.user.is_authenticated:
        return forums(request, warn=True)

    form = ForumForm()
    if request.method == "POST":
        form = ForumForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user.account
            instance.save()
            return redirect('forums:forums')

    context = {
        "form": form
    }
    return render(request, 'forums/add_forum.html', context)


def detail_forum(request, pk):
    forum = Forum.objects.get(id=pk)
    comment_form = CommentForm()
    context = {
        "forum": forum,
        "author": True,
        "warn": False
    }

    if request.user != forum.author.user:
        context['author'] = False

    if not request.user.is_authenticated:
        context['warn'] = True
        return render(request, 'forums/detail_forum.html', context)

    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            instance = comment_form.save(commit=False)
            instance.author = request.user.account
            instance.save()
            return redirect('forums:forums_detail_forum', pk)

    context['comment_form'] = comment_form
    return render(request, 'forums/detail_forum.html', context)


def delete_forum(request, pk):
    forum = Forum.objects.get(id=pk)
    if request.user != forum.author.user:
        return redirect('forums:forums_detail_forum', pk)
    if request.method == 'POST':
        forum.delete()
    return redirect('forums:forums')


def ajax_search(request):
    query = request.GET.get("search")

    forums = Forum.objects.filter(
        Q(caption__icontains=query) |
        Q(body__icontains=query))

    json_dump = json.loads(serialize('json', forums))
    updated_json = []
    for card in json_dump:
        author = Account.objects.get(id=card['fields']['author'])
        author_image = author.image
        author_name = author.name
        author_job = author.job
        id = card['pk']
        comments = Forum.objects.get(id=id).comments.count()
        card['fields']['author_image'] = author_image
        card['fields']['author_name'] = author_name
        card['fields']['author_job'] = author_job
        card['fields']['comments'] = comments
        updated_json.append(card)

    return JsonResponse(updated_json, safe=False)


def ajax_set_follow(request):
    pk = request.GET.get("id")

    forum = Forum.objects.get(id=pk)
    user = request.user.account

    action = request.GET.get("action")
    if action == 'add':
        forum.followed_by.add(user)
    else:
        forum.followed_by.remove(user)

    return JsonResponse(json.loads(serialize('json', Forum.objects.all())), safe=False)


def ajax_get_follow(request):

    user = request.user.account
    followed = user.forum_set.all()

    json_dump = json.loads(serialize('json', followed))
    updated_json = []
    for card in json_dump:
        author = Account.objects.get(id=card['fields']['author'])
        author_image = author.image
        author_name = author.name
        author_job = author.job
        id = card['pk']
        comments = Forum.objects.get(id=id).comments.count()
        card['fields']['author_image'] = author_image
        card['fields']['author_name'] = author_name
        card['fields']['author_job'] = author_job
        card['fields']['comments'] = comments
        updated_json.append(card)

    return JsonResponse(updated_json, safe=False)

forums/templates/forums/add_forum.html
{% extends 'APP1/base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href={% static 'forums/forums.css' %}>
<link rel="stylesheet" href={% static 'forums/add_forum.css' %}> {% endblock head %} {% block body %}
<div class="forums">
    <div class="container">
        <div class="title">
            Add Forum
        </div>
        <div class="row">
            <div class="col s12">
                <div class="card horizontal">
                    <div class="card-content">
                        <form method="post" action="{% url 'forums:forums_add_forum' %}">
                            {% csrf_token %}
                            <div>{{form.caption}}</div>
                            <div>
                                <label>Body</label> {{form.body}}
                            </div>
                            {{form.author}}
                            <input class="kenta-img-button kenta-med tooltipped" data-tooltip="Post forum"
                                id="add_forum" type="submit" name="" value="">
                            <input class="kenta-img-button kenta-med tooltipped" data-tooltip="Clear" id="clear"
                                type="reset" name="" value="">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %} {% block script %} {% endblock script %}

forums/templates/forums/detail_forum.html
{% extends 'APP1/base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href={% static 'forums/forums.css' %}>
<link rel="stylesheet" href={% static 'forums/detail_forum.css' %}> {% endblock head %} {% block body %}
<div class="forums">
    <div class="forum-detail">
        <div class="card horizontal">
            <div class="card-stacked">
                <div class="card-content">
                    <h4>
                        {{forum.caption}}
                    </h4>
                </div>
                <div class="card-content" style="opacity: 80%;">
                    <div style="opacity: 80%;">
                        <span>Created {{forum.timestamp | date:"F d Y"}}</span>
                    </div>
                    <div class="kenta-img-p-combo">
                        <img style="border-radius: 50%; width: 30px; height: 30px; object-fit: cover;" src="{{ forum.author.image }}"> {{forum.author.name}}
                    </div>
                </div>
                <div class="divider"></div>
                <div class="card-content">
                    <p style="font-size: 12pt; white-space: pre-wrap;">{{forum.body}}
                    </p>
                </div>
                <div class="card-content" style="display: flex; flex-direction: row;">
                    {% if author %}
                    <form method="post" action="{% url 'forums:forums_delete_forum' forum.id %}" style="height: 36px;">
                        {% csrf_token %}
                        <input class="kenta-img-button tooltipped" id="delete_forum" type="submit" value="" data-tooltip="Delete forum <br> and its comments">
                    </form>
                    {% endif %}
                    <div class="kenta-img-button tooltipped" id="comment" data-tooltip="Reply with comment" onclick='toggle_comment()'>
                    </div>
                </div>

            </div>
        </div>
        <div class="card horizontal" id="kenta-add-comment-toggle" style="overflow: hidden; width: 80%; height: 0px; transition: 0.2s;">
            <div class="card-content">
                <form method="POST" action="{% url 'forums:forums_detail_forum' forum.id %}">
                    <div style="display: flex; align-items: flex-end;">
                        {% csrf_token %}
                        <input type="hidden" name="forum" value="{{forum.id}}"> {% if warn %}
                        <div class="kenta-img-button kenta-med tooltipped" style="pointer-events:visible; opacity: 0.5; cursor: not-allowed;" data-tooltip="Post comment" id="add_comment"></div>
                        <div style="color: #DA4167; font-weight: 300pt; font-size: 12pt;background-color: #FFCECB; padding: 16px; width: 100%;">
                            You must be logged in before posting comments
                        </div>
                        {% else %}
                        <img style="border-radius: 50%; width: 30px; height: 30px; object-fit: cover; margin-right: 10px;" src={{request.user.account.image}} alt="">{{comment_form.body}} <input style="margin: 0 0 0 10px;" class="kenta-img-button kenta-med tooltipped" data-tooltip="Post comment" id="add_comment" type="submit" name="" value=""> {% endif %} 
                    </div>
                </form>
            </div>
        </div>
        {% if forum.comments.count > 0 %}
        <div class="card horizontal" style="width: 80%;">
            <div class="card-stacked">
                <div class="card-content">
                    <h5>
                        Comments
                    </h5>
                </div>
                {% for comment in forum.comments.all %}
                <div class="divider"></div>
                <div class="card-content">

                    <div class="kenta-img-p-combo">
                        <img style="border-radius: 50%; width: 30px; height: 30px; object-fit: cover;" src="{{ comment.author.image }}"> {{comment.author.name|truncatechars:8}}
                    </div>
                    <p style="border-top: 1px solid #3D2645; padding-top: 8px; white-space: pre-wrap; word-wrap: break-word;">{{comment.body}}</p>
                    <div class="extras">
                        <div style="opacity: 80%;">
                            <span>Posted {{ comment.timestamp|timesince }} ago</span>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock body %} {% block script %}
<script>
    function toggle_comment() {
        var toggle = document.getElementById("kenta-add-comment-toggle");
        var form = document.getElementById("id_body");
        if (toggle.style.height == "0px") {
            toggle.style.height = "104px";
            setTimeout(function() {
                toggle.style.height = "fit-content";
            }, 200)
        } else {
            if (form != null) {
                form.value = "";
                form.style.height = "46px";
            }
            toggle.style.height = "104px";

            setTimeout(function() {
                toggle.style.height = "0px";
            }, 1)
        }
    }
</script>
{% endblock script %}

forums/templates/forums/forums.html
{% extends 'APP1/base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href={% static 'news/news.css' %}>
<link rel="stylesheet" href={% static 'forums/forums.css' %}>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{% endblock head %} {% block body %}
<div class="forums">
    <div class="container">
        <div class="title">
            Forums
        </div>
        <div class="row">
            {% if request.user.is_authenticated %}
            <div class="switch">
                <label>
                    All forums
                    <input onchange="switchFollow(this)" type="checkbox">
                    <span class="lever"></span>
                    Followed by me
                </label>
            </div>
            {% endif %}
            <div class="input__news">
                <input placeholder="Search Forums" type="text" name="search" class="browser-default search__news"
                    autocomplete="off" id="">
            </div>
            <div class="divider" style="margin: 10px 0;"></div>
            <div class="col s12">
                <div class="card horizontal">
                    <div class="card-stacked">
                        <div class="card-content" style="display: flex; flex-direction: row; align-items: center;">
                            <a style="margin-right: 1rem;" href="{% url 'forums:forums_add_forum' %}">
                                <div class="kenta-img-button" id="add_forum"></div>
                            </a>
                            <span style="color: #15c06d; font-weight: 300pt; font-size: 12pt;">Add a new forum
                                discussion</span>
                        </div>
                        {% if warn %}
                        <div class="divider"></div>
                        <div class="card-content" style="padding: 16px;">
                            <div
                                style="color: #DA4167; font-weight: 300pt; font-size: 12pt;background-color: #FFCECB; padding: 16px;">
                                You must be logged in before creating a new forum
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="wrapper"></div>
        </div>
    </div>
</div>

{% endblock body %}

{% block script %}
<script>
    let followIcon = (data) => {
        return (data.fields.followed_by).includes(parseInt('{{request.user.account.id}}')) ? 'notifications' : 'notifications_none'
    }
    let followTooltip = (data) => {
        return (data.fields.followed_by).includes(parseInt('{{request.user.account.id}}')) ? 'Remove from <br> followed forums' : 'Add to <br> followed forums'
    }

    let forumCard = (data) =>
        `
        <div class="col s12" id="row_${data.pk}">
                    <div class="card horizontal">
                        <div class="card-stacked">
                            <div class="card-content">
                                <span class="truncate card-title">${data.fields.caption}</span>
                                <p class="truncate">${data.fields.body}</p>
                            </div>
                            <div class="card-content extras " style="padding: 0 24px; ">
                                <div style="opacity: 80%; ">
                                    <span>Created at ${convertDate(data.fields.timestamp)}</span>
                                </div>
                                <div class="kenta-img-p-combo ">
                                    <img style="border-radius: 50%; width: 30px; height: 30px; object-fit: cover;"
                                        src="${data.fields.author_image}">
                                        ${truncate(data.fields.author_name, 8)}, ${data.fields.author_job}
                                </div>
                                <div class="kenta-img-p-combo ">
                                    <img src="{% static 'forums/icon/comments.svg' %}"> ${data.fields.comments}
                                </div>
                            </div>
                            <div class="card-action ">
                                <span style="width:100%;"><a href="./${data.pk}">Join forum</a></span>
                                <i 
                                id_follow=${data.pk} 
                                data-position="top" 
                                data-tooltip="${followTooltip(data)}" 
                                style="cursor: pointer" 
                                class="tooltipped material-icons follow">${followIcon(data)}</i>
                                </div>
                        </div>
                    </div>
                </div>
    `

    let timer, timeoutVal = 1000;

    $(document).ready(function () {
        fetchRegular();

        $('.input__news').on({
            click: () => {
                if (!($('.search__news').is(':focus'))) {
                    getValue(1);
                }
            },
            input: () => {
                handleKeyPress()
            },
            keyup: () => {
                getValue(1)
            }
        })
    });

    function activateFollow() {
        $('.tooltipped').tooltip();

        $('.follow').each((index, value) => {
            $(value).click(function () {
                let pk = $(this).attr('id_follow');
                '{% if request.user.is_authenticated %}'
                if ($(this).html() == "notifications_none") {
                    $.ajax({
                        url: `/forums/set_follow/?id=${pk}&action=add`,
                        success: () => { $(this).text('notifications'); }
                    })
                } else {
                    $.ajax({
                        url: `/forums/set_follow/?id=${pk}&action=remove`,
                        success: () => { $(this).text('notifications_none'); }
                    })
                }
                $(this).attr('data-tooltip', $(this).attr('data-tooltip') === 'Add to <br> followed forums' ? 'Remove from <br> followed forums' : 'Add to <br> followed forums')
                $(this).tooltip('close');
                '{% else %}'
                $(value).addClass('modal-trigger')
                $(value).attr('href', '#modal1')

                $(value).parent().append(`
                    <div id="modal1" class="modal">
                    <div class="modal-content">
                        <h4>You must login first</h4>
                        <a href="{% url 'userProfile:login' %}">Login Here!</a>
                    </div>
                    </div>
                `)
                $('.modal').modal();
                '{% endif %}'
            })
        })
    }

    function switchFollow(el) {
        if ($(el).prop('checked')) {
            fetchFollow();
            $('.input__news').hide()
        } else {
            fetchRegular();
            $('.input__news').show()
        }
    }

    function truncate(string, int) {
        if (string.length < int) return string
        return string.slice(0, int) + "..."
    }

    function fetchFollow() {
        handleKeyPress();
        $.ajax({
            url: '{% url "forums:forums_get_follow" %}',
            success: (result) => {
                $(".wrapper").empty();
                $(".wrapper").append(
                    result.map(data => forumCard(data))
                );
                console.log(result)
            }
        }).then(data => {
            activateFollow();
            $('.follow').click(function () {
                let pk = $(this).attr('id_follow')
                $(`#row_${pk}`).remove();
            })
        });

    }

    function fetchRegular() {
        handleKeyPress();
        let query = $('.search__news').val();
        $.ajax({
            url: `/forums/search/?search=${query}`,
            success: (result) => {
                $(".wrapper").empty();
                $(".wrapper").append(
                    result.map(data => forumCard(data))
                );
            }
        }).then(data => {
            activateFollow();
        });
    }

    function convertDate(time) {
        let date = new Date(time)
        let localTime = new Date()

        let getHours = Math.floor((localTime.getTime() - date.getTime()) / (1000 * 3600))
        let Difference_In_Days = Math.floor((localTime.getTime() - date.getTime()) / (1000 * 3600 * 24))

        return `⏲ ${Difference_In_Days == 0
            ? getHours + ' hours ago'
            : Difference_In_Days == 1
                ? 'Yesterday'
                : Difference_In_Days + ' days ago'}`
    }

    function getValue() {
        window.clearTimeout(timer);
        pageNow = 1;
        timer = window.setTimeout(() => {
            fetchRegular()
        }, timeoutVal);
    }

    function handleKeyPress() {
        window.clearTimeout(timer);
        $(".wrapper").css({
            'text-align': 'center'
        })
        $(".wrapper").html(loader + "<p style='margin: 0'>loading...🦠</p>")
    }
</script>
{% endblock script %}