APP1/urls.py
from django.urls import path, include

from . import views

app_name = 'APP1'

urlpatterns = [
    path('', views.index, name='index'),
]

corona_app/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from feedback.views import olah

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('APP1.urls')),
    path('forums/', include('forums.urls')),
    path('news/', include('news.urls')),
    path('userProfile/', include('userProfile.urls')),
    path('feedback/', include('feedback.urls')),
    path('rate/', olah, name = "olah"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedback/urls.py
from django.urls import path

from . import views

app_name = 'feedback'

urlpatterns = [
    path('', views.home, name='feedback'),
    path('add/', views.home, name = 'add'),
    path('rate/', views.olah, name = 'olah'),
    path('add/rate/', views.olah, name = 'olah'),
]

forums/urls.py
from django.urls import path

from . import views

app_name = 'forums'

urlpatterns = [
    path('', views.forums, name='forums'),
    path('add_forum/', views.add_forum, name='forums_add_forum'),
    path('<int:pk>', views.detail_forum, name='forums_detail_forum'),
    path('delete_forum/<int:pk>', views.delete_forum, name='forums_delete_forum'),
    path('search/', views.ajax_search, name='forums_search'),
    path('set_follow/', views.ajax_set_follow, name='forums_set_follow'),
    path('get_follow/', views.ajax_get_follow, name='forums_get_follow'),
]

news/urls.py
from django.urls import path

from . import views

app_name = 'news'

urlpatterns = [
    path('', views.news, name='news'),
    path('<int:news_id>/<str:news_title>/', views.news_detail, name='news_detail'),
    path("search/", views.news_search_result, name="ajax_news"),
    path("likes/add/", views.add_likes, name="add_likes"),
    path("likes/remove/", views.remove_likes, name="remove_likes"),
    path("bookmarked/", views.ajax_bookmark, name="ajax_bookmark"),
    path("bookmark/remove/", views.remove_bookmark, name="API_remove_bookmark"),
    path("bookmark/add/", views.add_bookmark, name="API_add_bookmark")
]

userProfile/urls.py
from django.urls import path
from . import views

app_name = 'userProfile'

urlpatterns = [
	path('signup/',views.signup_view,name="signup"),
	path('logout/',views.logout_view,name="logout"),
	path('login/',views.login_view,name="login"),
	path('profile/',views.profile_view,name="profile"),
	path('picupdate/',views.picupdate,name="picUpdate"),
]

APP1/models.py
from django.db import models

# Create your models here.

APP1/views.py
from django.shortcuts import redirect, render
from news.models import News
from forums.models import Forum
from news.utils import retrieve_API
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# from forum.models import Forum
# Create your views here.


def index(request):
    retrieve_API()
    request.session['forums_item'] = Forum.objects.all().count()
    request.session['news_item'] = News.objects.all().count()
    context = {
        'list_news': News.objects.all().order_by('-timestamp')[:6]
    }
    return render(request, 'APP1/landing.html', context)

APP1/templates/APP1/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href={% static 'APP1/base.css' %}>
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'APP1/icon/icon.svg' %}" />

  {% block head %}

  {% endblock head %}

  <title>CoronaTracker Lite</title>


</head>

<body>
  

  <section class="navbar">
    <nav>
      <div class="nav-wrapper nav__mod">
        <a href={% url 'APP1:index' %} class="brand-logo left"><img class="logo__app"
            src={% static 'APP1/icon/logo-app.svg' %} alt=""></a>
        <a href="#" style="transform: translateX(10px);" data-target="mobile-demo" class="sidenav-trigger right"><i
            class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down mid__ul">
          {% with url_name=request.resolver_match.url_name%}
          <li class="mid__ul__li {% if url_name == 'forums' %}under__line{% endif %}">
            <a class="li__mod tooltipped" data-position="bottom" data-tooltip="Forum" href={% url 'forums:forums' %}>
              <img class="icon__mod" src="
              {% if url_name == 'forums' %}
                {% static 'APP1/icon/forum_filled.svg' %}
              {% else %}
                {% static 'APP1/icon/forum.svg' %}
              {% endif %}
              " alt="">

            </a>
          </li>
          <li class="mid__ul__li {% if url_name == 'news' %}under__line{% endif %}">
            <a class="li__mod tooltipped" data-position="bottom" data-tooltip="News" href={% url 'news:news' %}>
              <img class="icon__mod" src="
              {% if url_name == 'news' %}
                {% static 'APP1/icon/news_filled.svg' %}
              {% else %}
                {% static 'APP1/icon/news.svg' %}
              {% endif %}
              " alt="">
            </a>
          </li>
          <li class="mid__ul__li {% if url_name == 'feedback' %}under__line{% endif %}">
            <a class="li__mod tooltipped" data-position="bottom" data-tooltip="Feedback"
              href={% url 'feedback:feedback' %}>
              <img class="icon__mod" src="
              {% if url_name == 'feedback' %}
                {% static 'APP1/icon/feedback_filled.svg' %}
              {% else %}
                {% static 'APP1/icon/feedback.svg' %}
              {% endif %}
              " alt="">
            </a>
          </li>
          {%endwith%}
        </ul>

        <div class="login__div">
          <ul>
            <li>
              <a class="li__mod dropdown-trigger" data-target='dropdown1'>

                {% if request.user.is_authenticated %}
                <img class="icon__mod icon__mod2 profile__img" src="{{request.user.account.image}}">
                <div style="line-height: initial; margin-right: 10px;">
                  <span style="font-size: 13px;">Hello, </span> <br>
                  <span>{{request.user.account.name | title | truncatechars:8}}</span>
                </div>

                {% else %}
                <img class="icon__mod icon__mod2 profile__img" src={% static 'APP1/icon/profile.svg' %} alt="">
                <div style="line-height: initial; margin-right: 10px;">
                  <span style="font-size: 13px;">Hello, </span> <br>
                  <span>Sign in</span>
                </div>
                {% endif %}

                <i class="material-icons">expand_more</i>
              </a>
            </li>
          </ul>
          <ul id='dropdown1' class='dropdown-content'>

            {% if request.user.is_authenticated %}
            <li><a href="{% url 'userProfile:profile' %}">Dashboard</a></li>
            <li class="divider" tabindex="-1"></li>
            <li><a href={% url 'userProfile:logout' %}>Sign out</a></li>
            {% else %}
            <li><a href={% url 'userProfile:login' %}>Sign in</a></li>
            <li class="divider" tabindex="-1"></li>
            <li><a href={% url 'userProfile:signup' %}>Sign Up</a></li>
            {% endif %}

          </ul>
        </div>
      </div>
    </nav>

    <!-- INI SIDENAVNYA KLO MOBILE VIEW -->
    <ul class="sidenav right" id="mobile-demo">
      {% if request.user.is_authenticated %}

      <li>
        <div class="user-view">
          <div class="background" style="background: linear-gradient(179.01deg, #832161 0.82%, #DA4167 99.15%);">
          </div>
          <div style="display: flex; justify-content: left; align-items: center; margin-bottom: 5px;">

            <img class="icon__mod icon__mod2 profile__img" src="{{request.user.account.image}}">

            <a style="flex: .9;">
              <span style="margin: 0;font-size: 1.5rem;"
                class="white-text name">{{ request.user.account.name | title | truncatechars:8 }}</span>
            </a>
            <a class="link__profile" href="{% url 'userProfile:profile' %}">
              <i class="small material-icons">edit</i>edit
            </a>
          </div>
          <a style="padding: 5px 0;" class="link__profile">
            <i class="tiny material-icons">work</i>
            <span style="padding: 0 5px;" class="white-text email">
              {{ request.user.account.job | default:"Job" }},
              {{ request.user.account.age }}th
            </span>
          </a>
          <a style="padding: 5px 0 10px;" class="link__profile">
            <i class="tiny material-icons">email</i>
            <span style="padding: 0 5px;"
              class="white-text email">{{ request.user.account.email | default:"Email" }}</span>
          </a>
        </div>
      </li>
      {% endif %}

      <li>
        <div class="time relative">
          <i class="small material-icons">access_time</i>
          <span class="clock"></span>
        </div>
      </li>
      <li>
        <a style="display: flex;" href={% url 'forums:forums' %}>
          <img class="icon__mod icon__mod2" src={% static 'APP1/icon/forum.svg' %} alt="">
          Forums
          <span class="new badge new__badge">{{ request.session.forums_item }}</span>
        </a>
      </li>
      <li>
        <a style="display: flex;" href={% url 'news:news' %}>
          <img class="icon__mod icon__mod2" src={% static 'APP1/icon/news.svg' %} alt="">
          News
          <span class="new badge new__badge">{{ request.session.news_item }}</span>
        </a>
      </li>
      <li>
        <a style="display: flex;" href={% url 'feedback:feedback' %}>
          <img class="icon__mod icon__mod2" src={% static 'APP1/icon/feedback.svg' %} alt="">
          Feedback
        </a>
      </li>
      <li class="divider" tabindex="-1"></li>
      {% if request.user.is_authenticated %}
      <li>
        <a style="display: flex;" data-target='dropdown2' href={% url 'userProfile:logout' %}>
          <img class="icon__mod icon__mod2" src={% static 'APP1/icon/logout.svg' %} alt="">
          Logout
        </a>
      </li>
      {% else %}

      <li>
        <a style="display: flex;" data-target='dropdown2' href={% url 'userProfile:signup' %}>
          <img class="icon__mod icon__mod2" src={% static 'APP1/icon/signup.svg' %} alt="">
          Sign Up
        </a>
      </li>
      <li>
        <a style="display: flex;" data-target='dropdown2' href="{% url 'userProfile:login' %}">
          <img class="icon__mod icon__mod2" src={% static 'APP1/icon/login.svg' %} alt="">
          Login
        </a>
      </li>
      {% endif %}
    </ul>
  </section>

  <div id="clock" class="time hide-on-med-and-down">
    <i class="small material-icons">access_time</i>
    <span class="clock"></span>
  </div>
  <div class="body__container">
    {% block body %}


    {% endblock body %}
  </div>

  <footer style="text-align: center; padding: 10px;" class="page-footer">
    Made with ❤ by C07
  </footer>



  <!-- Compiled and minified JavaScript -->
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <script>
    const loader =
      `<div class="preloader-wrapper big active"> <div class="spinner-layer spinner-blue"> <div class="circle-clipper left"> <div class="circle"></div></div><div class="gap-patch"> <div class="circle"></div></div><div class="circle-clipper right"> <div class="circle"></div></div></div><div class="spinner-layer spinner-red"> <div class="circle-clipper left"> <div class="circle"></div></div><div class="gap-patch"> <div class="circle"></div></div><div class="circle-clipper right"> <div class="circle"></div></div></div><div class="spinner-layer spinner-yellow"> <div class="circle-clipper left"> <div class="circle"></div></div><div class="gap-patch"> <div class="circle"></div></div><div class="circle-clipper right"> <div class="circle"></div></div></div><div class="spinner-layer spinner-green"> <div class="circle-clipper left"> <div class="circle"></div></div><div class="gap-patch"> <div class="circle"></div></div><div class="circle-clipper right"> <div class="circle"></div></div></div></div>`;
  </script>
  <script type="text/javascript">
    $(document).ready(function () {
      $('.sidenav').sidenav({
        edge: 'right',
        preventScrolling: 'false'
      });

      $('.tooltipped').tooltip({
        margin: -5,
        inDuration: 100,
        outDuration: 100,
        enterDelay: 0
      });
    })

    $('.dropdown-trigger').dropdown({
      closeOnClick: false,
      coverTrigger: false
    });

  </script>
  <script type="text/javascript">
    function startTime() {
      var today = new Date();
      var h = today.getHours();
      var m = today.getMinutes();
      var s = today.getSeconds();
      m = checkTime(m);
      s = checkTime(s);
      $('.clock').html(h + ":" + m + ":" + s)
      setTimeout(startTime, 1000);
    }

    function checkTime(i) {
      if (i < 10) {
        i = "0" + i
      }; // add zero in front of numbers < 10
      return i;
    }
    startTime()
  </script>
  <script>
    var prevScrollpos = window.pageYOffset;
    window.onscroll = function () {
      var currentScrollPos = window.pageYOffset;
      if (prevScrollpos > currentScrollPos) {
        document.getElementById("clock").style.top = "64px";
      } else {
        document.getElementById("clock").style.top = "-50px";
      }
      prevScrollpos = currentScrollPos;
    }
  </script>
  {% block script %}

  {% endblock script %}

</body>

</html>

APP1/templates/APP1/landing.html
{% extends 'APP1/base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.css" />
<link rel="stylesheet" href={% static 'APP1/landing.css' %}>
{% endblock head %}


{% block body %}
<div class="landing__app container__mod">
  <div class="content__wrapper max__500">
    <div class="landing__div">
      <div class="alert">⚠ Covid-19 Alert</div>
      <h4 class="landing__h4">
        Let's Protect Yourself From
        <span>COVID-19 💉</span>
      </h4>
    </div>

    <p class="landing__text">
      <b>COVID-19</b> affects different people in different ways.
      Protect yourself and others around you by knowing the facts and taking appropriate precautions.
      (who.int)
    </p>

    <button class="hoverable btn__first">Covid-19 Threat </button>
    <button data-target="modal1" class="tooltipped modal-trigger" data-position="right" data-tooltip="Watch Demo"
      style="width: 46px;">▶</button>

    <iframe id="modal1" class="embedvid modal" width="100%" height="60%" src="https://www.youtube.com/embed/FC4soCjxSOQ"
      frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowfullscreen>
    </iframe>

  </div>
  <img class="corona__group" src={% static 'APP1/img/corona-group.png' %} alt="">
  <img class="corona__solo" src={% static 'APP1/img/corona-solo.png'%} alt="">
</div>

<div class="status__cov container__mod" id="more">

  <img src={% static 'APP1/img/map.png' %} class="map" alt="">

  <div class="content__wrapper">
    <h4 class="recent__post__title pink1" style="color: #ffe0de;">Covid-19 Cases</h4>
    <select class="browser-default select__mod" name="country" id="countryId">
    </select>

    <div class="inline__block">
      <div class="card__cov">
        <p>Recovered <span id="incRecovery" style="color: #3ae794;"></span></p>
        <div class="stat" id="recover">
          <img src={% static 'APP1/icon/recovery-white.svg' %} alt="">
          <p id="recovered"></p>
        </div>
      </div>

      <div class="card__cov">
        <p>Confirmed <span id="incPositive" style="color: #ffba52;"></span></p>
        <div class="stat" id="positif">
          <img src={% static 'APP1/icon/positive-white.svg' %} alt="">
          <p id="positive"></p>
        </div>
      </div>

      <div class="card__cov">
        <p>Deaths <span id="incDeath" style="color: #ffa4bb;"></span></p>
        <div class="stat" id="death">
          <img src={% static 'APP1/icon/dead-white.svg' %} alt="">
          <p id="deaths"></p>
        </div>
      </div>

    </div>
    <div id="last_updated" style="font-style: italic;"></div>
  </div>
</div>

<div class="recent__post container__mod">
  <div class="content__wrapper">

    <img class="corona__img" src={% static 'APP1/img/corona-post.png' %} alt="">
    <h4 class="recent__post__title">Recent News</h4>
    <div class="row main-carousel">

      {% for news in list_news %}
      <div class="col s12 m6 l4 carousel-cell">
        <div class="card large card__large hoverable">
          <div class="card-image activator waves-effect waves-block waves-light card__img">
            <a href={% url 'news:news_detail' news.pk news.title|lower|slugify %}>
              <img src={{ news.image_url }} onerror="this.src='/static/news/news_default.svg'">
            </a>
          </div>
          <div class="card-content">
            <span class="card-title grey-text text-darken-4 ">
              <span class="card__title">{{ news.title }}</span>
            </span>
            <p class="card__content">
              <span style="color: rgb(141, 141, 141);">{{news.timestamp|date:"l, j F Y"}}</span>
              <a href={% url 'news:news_detail' news.pk news.title|lower|slugify %}>More →</a>
            </p>
          </div>
        </div>
      </div>
      {% endfor %}

    </div>
  </div>
</div>
{% endblock body %}


{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.js"></script>
<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
<script>
  $(document).ready(function () {
    $('.modal').modal({
      onCloseEnd: stopVideo
    });
    $('.main-carousel').flickity({
      // options
      cellAlign: 'center',
      contain: false,
      autoPlay: 3000,
      groupCells: 1,
      prevNextButtons: false,
      draggable: true
    });

    fetchCountry('IDN');
    // jquery event 1
    $('#countryId').on('change', function () {
      fetchCountry(this.value);
    });
    // jquery event 2
    $('.btn__first').click(function () {
      let offsetCovCases = $('.status__cov').offset().top
      let navHeight = $('.nav__mod').outerHeight()
      $(window).scrollTop(offsetCovCases - navHeight)
    })
  });

  // perubahan HTML attr
  function stopVideo() {
    $('.embedvid').attr('src', "https://www.youtube.com/embed/FC4soCjxSOQ");
  }

  function formatNumber(num) {
    return num.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1,')
  }

  function fetchCountry(country) {
    // perubahan HTML attr
    $('.inline__block').children().hide()
    $('.inline__block').append(loader);

    $.ajax({
        url: `https://disease.sh/v3/covid-19/countries/${country}`,
        success: (data) => {
          let date = new Date(data.updated);
          let days = date.toLocaleString("en-US", {
            weekday: "long"
          })
          let day = date.toLocaleString("en-US", {
            day: "numeric"
          })
          let month = date.toLocaleString("en-US", {
            month: "long"
          })
          let year = date.toLocaleString("en-US", {
            year: "numeric"
          })
          $('#last_updated').html(`***Last updated ${days}, ${day} ${month} ${year}`)
          $('#deaths').html(formatNumber(data.deaths))
          $('#incDeath').html(`(+${formatNumber(data.todayDeaths)})`)
          $('#positive').html(formatNumber(data.cases))
          $('#incPositive').html(`(+${formatNumber(data.todayCases)})`)
          $('#recovered').html(formatNumber(data.recovered))
          $('#incRecovery').html(`(+${formatNumber(data.todayRecovered)})`)
        }
      })
      .then(e => {
        $('.inline__block').children().show()
        $('.inline__block').children().remove('.preloader-wrapper')
      })
  }
</script>

<script type="text/javascript">
  function custom_template(obj) {
    var data = $(obj.element).data();
    var text = $(obj.element).text();
    if (data && data['img_src']) {
      img_src = data['img_src'];
      template = $(`
        <div>
          <img src="${img_src}" style="width:36px;height:36px;"/>
          <p style="font-weight: 600;font-size:14px;text-align:center;">${text}</p>
        </div>`);
      return template;
    }
  }

  var options = {
    'templateSelection': custom_template,
    'templateResult': custom_template,
  }

  $.ajax({
    url: 'https://disease.sh/v3/covid-19/countries',
    success: (data) => {
      data.forEach(country => {
        $('#countryId').append(`
        <option 
        value="${country.countryInfo.iso3}" 
        ${country.countryInfo.iso3=='IDN'?'selected':''} 
        data-img_src="${country.countryInfo.flag}">
          ${country.country}
        </option>
      `);
      });
    }
  })
  .then(e => {
    $('#countryId').select2(options);
    $('.select2-container--default').css({
      'display': 'block',
      'margin': 'auto',
      'border-radius': '24px'
    });
    $('.select2-selection--single').css({
      'border-radius': '24px'
    });
    $('.select2-search__field').css({
      'width': '20%'
    });
    // jquery event 
    $('.select2-selection').on('click', function () {
      $('.select2-search__field').addClass('browser-default');
    })
  });
</script>

{% endblock script %}